### PR TITLE
156/fix error messages

### LINKED ISSUE #156: Fix error messages
- [x] Capitalize error messages
- [x] When getting something that does not exist in the db (`GET /api/item/999` for example), the error message is `does not exist`. It would be nice to mention what does not exist and return a message more like `Item does not exist`. This happens for every entity I tried (item, brand, etc.).
- [x] When logging in, incorrect credentials should return something like `Invalid email or password` instead of `row does not exist`.

### PR DESCRIPTION
**Pull request by AdamVig**
Closes #156.

### CODE REVIEW

File: controllers/auth.js [hunk 1]
```diff
@@ -115,7 +118,7 @@ auth.register = (req, res, next) => {
       .then(([userID]) => {
         return res.send(201, {
           id: userID,
-          message: 'registered user'
+          message: 'Registered user successfully'
```
Comment (emroussel) [inline controllers/auth.js]: Could this be `User successfully registered` to be consistent with the messages on the front end? Just because that's the sentence structure I used.

**Review by emroussel — CHANGES_REQUESTED** [review]
The successful messages on the front end have an exclamation point at the end. Do you think that makes sense to have? Whatever we choose (exclamation point or not), it should be consistent between the api and the app.

File: controllers/auth.js (hunk 1 above)
Comment (AdamVig) [reply controllers/auth.js]: Sure, that works.

**Comment by AdamVig** [comment]
I think we should leave the exclamation points off, because they seem a little bit *too* friendly. Do you have a strong opinion one way or the other?

**Comment by emroussel** [comment]
Yeah I think so too

**Review by emroussel — APPROVED** [review]
