### PR TITLE
251/Rent multiple items

### LINKED ISSUE #251: Add rent multiple items endpoint
This endpoint should use a transaction to rent items so that rentals are all-or-nothing. It is currently possible for part of a rental to fail when just one item conflicts with an existing rental.

- [x] Change the old rent route to take requests that don't have a `Version` header
- [x] Add a new rent route that accepts batch rentals

### PR DESCRIPTION
**Pull request by AdamVig**
Closes #251.

### CODE REVIEW

File: controllers/auth.js [hunk 1]
```diff
@@ -36,6 +36,7 @@ auth.mount = app => {
    * @api {post} /auth Authenticate a user
    * @apiName Authenticate
    * @apiGroup Authentication
+   * @apiVersion 2.0.0
```
Comment (emroussel) [inline controllers/auth.js:39]: Is there a way to have a global api version instead of changing it on every endpoint every time the version changes?

**Review by emroussel — APPROVED** [review]

File: controllers/auth.js (hunk 1 above)
Comment (AdamVig) [reply controllers/auth.js:39]: I looked and couldn't find anything. I did want to experiment with only providing the version on the old endpoints - maybe, if no version is provided, apiDoc will default to the current version. I'll try that, and if it doesn't work, we'll be stuck with how it currently is.
